---
- name: Delete Azure ResourceGroup
  hosts: localhost
  connection: local
  gather_facts: false

  collections:
    - azure.azcollection

  tasks:

    - name: Delete Resource Group - "{{ rgname }}"
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ rgname }}"
        force_delete_nonempty: yes
        state: absent
    - debug:
        var: rgname
